### ISSUE TITLE
Is there a way to generate the mapper classes and interfaces?

### ISSUE THREAD

**Issue by georgewei** [chenggangpro/reactive-mybatis-support-examples#2]
I'm very interested in this example project, and I'm trying to create one. How can I generate the pro.chenggang.example.reactive.mybatis.r2dbc.spring.mapper.**.* files?

**Comment by chenggangpro** [comment]
* The original generator is [mybatis-generator](https://github.com/mybatis/generator)
* The java based dynamic sql's original project is [mybatis-dynamic-sql](https://github.com/mybatis/mybatis-dynamic-sql)
* The reactive dynamic sql generator is the project that I adapt original `mybatis-dynamic-sql` and `mybatis-generator` with [reactive-mybatis-support](https://github.com/chenggangpro/reactive-mybatis-support)'s `mybatis-r2dbc-generator`,more details are in [using-mybatis-dynamic-sql](https://github.com/chenggangpro/reactive-mybatis-support#using-mybatis-dynamic-sql) and [mybatis-r2dbc-generator](https://github.com/chenggangpro/reactive-mybatis-support/tree/main/mybatis-r2dbc-generator) 
* In those examples that you mentioned, the generator's configuration is 
[src/main/resources/mybatis-generator.yml](https://github.com/chenggangpro/reactive-mybatis-support-examples/blob/master/mybatis-r2dbc-spring-example/src/main/resources/mybatis-generator.yml)
and the generator's running entrypoint is
[src/test/java/pro/chenggang/example/reactive/mybatis/r2dbc/spring/MyBatisGeneratorAction.java](https://github.com/chenggangpro/reactive-mybatis-support-examples/blob/master/mybatis-r2dbc-spring-example/src/test/java/pro/chenggang/example/reactive/mybatis/r2dbc/spring/MyBatisGeneratorAction.java)

I hope those information could be helpful

**Comment by chenggangpro** [comment]
This issue is out of date , reopen it if necessary
