### ISSUE TITLE
Code Generation Broken.

### ISSUE THREAD

**Issue by jeganathan-shyam** [chenggangpro/reactive-mybatis-support-examples#4]
We have a test class MyBatisGeneratorAction.java that generates DeptMapper.xml and associated interface DeptMapper.java; The code generation seems to be broken. The interface generated does NOT have any methods in it, whereas, the code that is checked-in has multiple methods in this interface. Can you please check and let us know?
[DeptMapper.zip](https://github.com/chenggangpro/reactive-mybatis-support-examples/files/10041540/DeptMapper.zip)

**Comment by chenggangpro** [comment]
Hi～，
        The purpose of `MyBatisGeneratorAction` class is to generate the Mapper interface and mapper-xml corresponding to the database for the first time. The `MyBatisGeneratorAction ` is a simplified run based on the `mybatis-generator` framework by replacing xml with yaml ,it runs in a `@Test` method or a `main` method instead of the original way in  `mybatis-generator` framework .I have added `@Disabled` annotation method at `MyBatisGeneratorAction`'s method in case of that would not run generate method automatically.

**Comment by jeganathan-shyam** [comment]
Hi,
Thank you so much for your time and response. So, I now understand this is a feature. However, I would like to generate all the methods in the interface along with the same in the .xml file. When you say you have replaced the .xml wih .yaml you mean the configuration yml- mybatis-generator.yml?

`@Mapper
public interface DeptMapper extends DeptDynamicMapper {

    Mono<Long> countAll();

    Flux<Dept> selectAll();

    Mono<Dept> selectOneByDeptNo(Long deptNo);

    Flux<Dept> selectListByTime(LocalDateTime createTime);

    Mono<Integer> insertOne(Dept dept);

    Mono<Integer> insertUseSelectKey(Dept dept);

    Mono<Integer> deleteByDeptNo(Long deptNo);

    Mono<Integer> updateByDeptNo(Dept dept);

    Flux<DeptWithEmp> selectDeptWithEmpList();
}`

I would like my generated interface to look like the one checked in the repository as above- with all the relevant methods since I need those methods for use in business logic. How do I go about doing that? Thank you for your efforts in this project.

**Comment by jeganathan-shyam** [comment]
I think I understand this better... you generated the skeleton and then manually added these interface methods along with manually adding to the corresponding xml files? But as I recall, though I am not completely sure, the original mybatis generator used to generate a lot of these methods - not all the methods you have but quite a large number of these methods rather than an empty interface.

Can you please clarify?

**Comment by chenggangpro** [comment]
> I think I understand this better... you generated the skeleton and then manually added these interface methods along with manually adding to the corresponding xml files? But as I recall, though I am not completely sure, the original mybatis generator used to generate a lot of these methods - not all the methods you have but quite a large number of these methods rather than an empty interface.
> 
> Can you please clarify?

Yes,It is 🤣. Like the code shows : `interface DeptMapper` extends `interface DeptDynamicMapper`.The `DeptDynamicMapper` has many methods whose generated by `mybatis-generator` automatically. The `DeptMapper ` has no method generated.This is intentional.

* If sql code is written by `xml` then write mapper method in `DeptMapper ` manually
* If sql code is written by `mybatis-dynamic-sql` programmatically then write mapper method in `DeptMapper ` that should use super method in `DeptDynamicMapper` like:
```java
@Mapper
public interface DeptMapper extends DeptDynamicMapper {

    default Mono<Dept> selectOneByDeptNo(Long deptNo){
        return selectOne(dsl -> dsl.where(DeptDynamicSqlSupport.deptNo, SqlBuilder.isEqualTo(deptNo)));
    }
}
```
I customized the behavior of the mybatis generator to disable the original generation methods you mentioned .

The main purpose is to combine two programming mode in one place.(Here's a bit of my own programming habits )

**Comment by jeganathan-shyam** [comment]
OK, thank you so much for your time and clarification, closing this item now.
